"""Configuration module for Pichu."""

from config.config import (
    ApprovalConfig,
    ApprovalPolicy,
    Config,
    GlobConfig,
    GrepConfig,
    HookHandlerConfig,
    HookMatcherConfig,
    HooksConfig,
    LLMConfig,
    LoggingAuditConfig,
    LoggingConfig,
    LoggingConsoleConfig,
    LoggingFileConfig,
    LoggingRedactionConfig,
    LimitsConfig,
    LoopDetectionConfig,
    MCPServerConfig,
    MemoryConfig,
    PermissionRulesConfig,
    RetryConfig,
    SafetyConfig,
    SafetySandboxConfig,
    SessionPersistenceConfig,
    ShellConfig,
    WebFetchConfig,
    WebSearchConfig,
    get_config,
    reset_config,
    set_config,
)
from config.loader import (
    create_default_config_file,
    ensure_config_dir,
    get_config_dir,
    get_system_config_path,
    load_config,
)

__all__ = [
    # Schema types
    "Config",
    "LLMConfig",
    "LimitsConfig",
    "RetryConfig",
    "LoggingConfig",
    "LoggingConsoleConfig",
    "LoggingFileConfig",
    "LoggingAuditConfig",
    "LoggingRedactionConfig",
    "ShellConfig",
    "SafetyConfig",
    "SafetySandboxConfig",
    "GlobConfig",
    "GrepConfig",
    "WebSearchConfig",
    "WebFetchConfig",
    "MemoryConfig",
    "MCPServerConfig",
    "ApprovalConfig",
    "ApprovalPolicy",
    "PermissionRulesConfig",
    "HooksConfig",
    "HookMatcherConfig",
    "HookHandlerConfig",
    "LoopDetectionConfig",
    "SessionPersistenceConfig",
    # Singleton
    "get_config",
    "set_config",
    "reset_config",
    # Loading and bootstrap
    "load_config",
    "get_config_dir",
    "get_system_config_path",
    "ensure_config_dir",
    "create_default_config_file",
]
